[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vccweb"
version = "0.2.0"
description = "HVP Virome Characterization Center (VCC) sample browser"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "SQLAlchemy~=2.0"
    "Flask~=2.0",
    "flask_sqlalchemy~=3.1",
    "gunicorn",
]

[project.scripts]
vccweb = "vccweb.cli:main"
